import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <title>Kamalveer Singh</title>
        <meta
          name="description"
          content="Personal portfolio of Kamalveer Singh"
        />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap');
        </style>
      </head>
      <body
        className="min-h-full flex flex-col space-grotesk bg-[#0C1117] text-gray-300"
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
